config/routes.rb
Rails.application.routes.draw do
  resources :heros

end

app/models/hero.rb
class Hero < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all.order(id: :desc)
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :hero_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<%= form_for(@hero) do |f| %>
  <% if @hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% @hero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :hero_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heros/edit.html.erb
<h1>Editing hero</h1>

<%= render 'form' %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<h1>Listing heros</h1>
<table>
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Type</th>
      <th scope="colgroup" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.name %></td>
        <td><%= hero.hero_type %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Hero', new_hero_path %>

app/views/heros/new.html.erb
<h1>New hero</h1>

<%= render 'form' %>

<%= link_to 'Back', heros_path %>

app/views/heros/show.html.erb
<p id="notice"><%= notice %></p>
<p><strong>Name</strong> <%= @hero.name %></p>
<p><strong>Type</strong> <%= @hero.hero_type %></p>
<%= link_to 'Edit', edit_hero_path(@hero) %> | <%= link_to 'Back', heros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeroesTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>